---
title: "2_LSC2_secchi_matchup"
author: "B Steele"
date: "2023-03-03"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(tibbletime)
```

# Purpose

To create a match up database of the Landsat record and historical Secchi data for Yojoa.

# Bring in the data

```{r}
secchi = read_xlsx('data/Secchi_completedataset.xlsx') %>% 
  mutate(date = as.Date(date)) 
str(secchi)

ls = read.csv('data/Yojoa_LandsatC2_SRST_filtered_v2023-03-16.csv') %>% 
  mutate(date = as.Date(date))
str(ls)
```

And join them together (this is the list of 1:1 matchups)

```{r}
sameDay_matchups = inner_join(secchi, ls)
```

And now we can move out from there:

```{r}
secchi = secchi %>% 
  rename(obs_date = date) %>% 
  as_tbl_time(secchi, index = obs_date) %>% 
  arrange(obs_date) 
ls4 = ls %>% 
  filter(mission == 'LANDSAT_4') %>% 
  as_tbl_time(., index = date) %>% 
  arrange(date)
ls5 = ls %>% 
  filter(mission == 'LANDSAT_5') %>% 
  as_tbl_time(., index = date) %>% 
  arrange(date)
ls7 = ls %>% 
  filter(mission == 'LANDSAT_7') %>% 
  as_tbl_time(., index = date) %>% 
  arrange(date)
ls8 = ls %>% 
  filter(mission == 'LANDSAT_8') %>% 
  as_tbl_time(., index = date) %>% 
  arrange(date)
ls9 = ls %>% 
  filter(mission == 'LANDSAT_9') %>% 
  as_tbl_time(., index = date) %>% 
  arrange(date)


filterInWindow = function(window, dt) {
  L4 = ls4 %>% 
    filter_time(dt-days(window) ~ dt+days(window)) %>% 
    mutate(obs_date = dt) %>% 
    merge(secchi, .)
  L5 = ls5 %>% 
    filter_time(dt-days(window) ~ dt+days(window)) %>% 
    mutate(obs_date = dt) %>% 
    merge(secchi, .)
  L7 =ls7 %>% 
    filter_time(dt-days(window) ~ dt+days(window)) %>% 
    mutate(obs_date = dt) %>% 
    merge(secchi, .)
  L8 =ls8 %>% 
    filter_time(dt-days(window) ~ dt+days(window)) %>% 
    mutate(obs_date = dt) %>% 
    merge(secchi, .)
  L9 = ls9 %>% 
    filter_time(dt-days(window) ~ dt+days(window)) %>% 
    mutate(obs_date = dt) %>% 
    merge(secchi, .)
  rbind(L4, L5) %>% rbind(., L7) %>% rbind(.,L8) %>% rbind(.,L9)
}

# these take a few minutes because of the inner join.
oneDay_matchups = map2_dfr(1, as.Date(secchi$obs_date), filterInWindow)
twoDay_matchups = map2_dfr(2, as.Date(secchi$obs_date), filterInWindow)
threeDay_matchups = map2_dfr(3, as.Date(secchi$obs_date), filterInWindow)
fiveDay_matchups = map2_dfr(5, as.Date(secchi$obs_date), filterInWindow)

#remove the dupes (why these are happening I honestly don't know.)
oneDay_matchups=oneDay_matchups[!duplicated(oneDay_matchups),]
twoDay_matchups=twoDay_matchups[!duplicated(twoDay_matchups),]
threeDay_matchups=threeDay_matchups[!duplicated(threeDay_matchups),]
fiveDay_matchups=fiveDay_matchups[!duplicated(fiveDay_matchups),]

```

## Export matchups

```{r}
write.csv(sameDay_matchups, 'data/sameDay_LS-Secchi_matchups.csv', row.names = F)
write.csv(oneDay_matchups, 'data/oneDay_LS-Secchi_matchups.csv', row.names = F)
write.csv(twoDay_matchups, 'data/twoDay_LS-Secchi_matchups.csv', row.names = F)
write.csv(threeDay_matchups, 'data/threeDay_LS-Secchi_matchups.csv', row.names = F)
write.csv(fiveDay_matchups, 'data/fiveDay_LS-Secchi_matchups.csv', row.names = F)
```
